### ISSUE TITLE
Instructions on fields in the Buildamic builder display twice

### ISSUE THREAD

**Issue by jelleroorda** [HandmadeWeb/buildamic#10]
## Bug Description
Instructions on fields in the Buildamic builder display twice.

## How to Reproduce
Add some instructions for a field in the builder, and look at how it renders when editing entries.

## Extra Detail
![Schermafbeelding 2021-09-03 om 12 02 29](https://user-images.githubusercontent.com/9193686/132000297-065201c7-a54e-41df-8069-9062d739cf3c.png)

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.6
edalzell/blade-directives 3.5
handmadeweb/buildamic dev-main

**Comment by michaelr0** [comment]
Thanks Jelle,

The bottom instruction was the original that we had, but we had some issues with replicators which prompted us to nest Fields within Statamics publish-field, which seems to include the instruction below the title.

This should now be resolved in https://github.com/HandmadeWeb/buildamic/commit/a6f0bae83c5aedb6232fc4a7ad14202689c9363a

**Comment by jelleroorda** [comment]
Hi Michael, this is indeed now resolved 🎉
