### ISSUE TITLE
Save button missing when editing Buildamic sections/rows/fields.

### ISSUE THREAD

**Issue by jelleroorda** [HandmadeWeb/buildamic#13]
## Bug Description
I missed the ‘save’ button when opening the settings of sections/rows/fields. If I’m not mistaken drawers have a save button usually in the top right corner of the drawer.

**Example when editing Statamic blueprints:**

![Schermafbeelding 2021-09-03 om 14 02 51](https://user-images.githubusercontent.com/9193686/132002256-7bd129f9-336f-4390-9185-6257beac1056.png)

When I opened the settings for the first time i wasn’t sure whether it would save my settings when clicking to the side of the drawer. Without a button it’s also impossible to close the drawer when on mobile.

## How to Reproduce
Open the settings of a section/row/field in the Buildamic builder.

## Extra Detail
![Schermafbeelding 2021-09-03 om 14 04 18](https://user-images.githubusercontent.com/9193686/132002413-468de493-9ad0-4913-87c9-81fd33741962.png)

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.6
edalzell/blade-directives 3.5
handmadeweb/buildamic dev-main

**Comment by michaelr0** [comment]
@sliver37 we should probably add a close button onto these stacks, I have also noticed that I tend to click to the far left to get back out of them.

**Comment by michaelr0** [comment]
@sliver37 this was resolved recently wasn't it?
