### ISSUE TITLE
Margin/padding box enlarges when clicking on it

### ISSUE THREAD

**Issue by jelleroorda** [HandmadeWeb/buildamic#15]
## Bug Description
Not sure why this is happening, or why this feature exists?

## How to Reproduce
Click on anything in the box, clicking outside shrinks it again.

## Extra Detail
https://user-images.githubusercontent.com/9193686/132002826-eebdf5bf-42de-4298-94eb-8cd865668fe5.mov

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.6
edalzell/blade-directives 3.5
handmadeweb/buildamic dev-main

**Comment by sliver37** [comment]
This was just a temporary thing as I was originally going to make it smaller and the animation was going to scale it to a usable size and move it to the middle of the modal, fading out the background elements so only the margin/padding was in focus. 

I *think* it's fine in this location now and still readable enough, if a little on the smaller side.
