### ISSUE TITLE
Add a drag handle to the sections/rows/fields in the builder

### ISSUE THREAD

**Issue by jelleroorda** [HandmadeWeb/buildamic#17]
## Bug Description
Maybe we can add a drag handle to fields/rows/sections to make it more clear that you can drag them? Preferably we would make it look the same as the other drag handles used in Statamic.

N.B. very nice that this dragging is possible 💯 .

## Extra Detail
See here how it looks now vs. how Statamic handles it.

![Schermafbeelding 2021-09-03 om 14 15 14](https://user-images.githubusercontent.com/9193686/132003719-341238bc-b3c8-4288-9730-5997e2815fc9.png)

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.6
edalzell/blade-directives 3.5
handmadeweb/buildamic dev-main

**Comment by sliver37** [comment]
Good idea, these will make the UI more understandable at a glance.

![image](https://user-images.githubusercontent.com/998827/156606016-a21e3ef6-b1c3-4682-a057-55cc5ce096cc.png)
