### ISSUE TITLE
Have the options on rows be displayed on the left consistently.

### ISSUE THREAD

**Issue by jelleroorda** [HandmadeWeb/buildamic#18]
## Bug Description
It would probably be best to move the settings for every section to the left side for consistency’s sake. Not sure why that section has the settings in the bottom?

## Extra Detail
![Schermafbeelding 2021-09-03 om 12 17 44](https://user-images.githubusercontent.com/9193686/132003904-61b7ca2b-df06-401d-aed4-2d635e383d5c.png)

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.6
edalzell/blade-directives 3.5
handmadeweb/buildamic dev-main

**Comment by sliver37** [comment]
Agree, too confusing when it's not consistent. Fixed
