### ISSUE TITLE
Make the 'add row' button full width

### ISSUE THREAD

**Issue by jelleroorda** [HandmadeWeb/buildamic#19]
## Bug Description
When creating a new section, I think the ‘Add row’ button could be 100% width.

## How to Reproduce
Create a new section, and see the 'add row' button.

## Extra Detail
![Schermafbeelding 2021-09-03 om 14 19 22](https://user-images.githubusercontent.com/9193686/132004110-f86b1575-fee7-40c7-bd4d-bd2dc309ae6f.png)

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.6
edalzell/blade-directives 3.5
handmadeweb/buildamic dev-main

**Comment by sliver37** [comment]
Fixed
