### ISSUE TITLE
laravel 9 issue

### ISSUE THREAD

**Issue by breizhwave** [HandmadeWeb/buildamic#31]
Hi,  I would like to try the buildamic but laravel 9 says

 Problem 1
    - Root composer.json requires handmadeweb/buildamic dev-main -> satisfiable by handmadeweb/buildamic[dev-main].
    - handmadeweb/buildamic dev-main requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).

You can also try re-running composer require with an explicit version constraint, e.g. "composer require handmadeweb/buildamic:*" to figure out if any version is installable, or "composer require handmadeweb/buildamic:^2.1" if you know which you need.

**Comment by michaelr0** [comment]
Hi @breizhwave,

Thanks for the heads up, I’ll have a look into Laravel 9 and see if Buildamic works with it, if it does, or if I can make the needed changes, then I will update the composer json and let you know the outcome.

**Comment by michaelr0** [comment]
Hi @breizhwave,

This should now be installable with Laravel 9, since the changes made [here](https://github.com/HandmadeWeb/buildamic/commit/6f2ac37f9696ce208d5dcac9cc6fd3e1199161ca) and [here](https://github.com/HandmadeWeb/hookable-actions-filters/commit/b1fe0cbd63d670fb831aab5bff2d951a1ccf2824)

**Comment by breizhwave** [comment]
great thks a millions, it works , well done for your work, just starting to test and works fine !! great work
