### ISSUE TITLE
Missing the SVG icons

### ISSUE THREAD

**Issue by jelleroorda** [HandmadeWeb/buildamic#8]
## Bug Description
After installing the Buildamic addon through composer, there seem to be a few assets that do not load or are missing. I tried publishing all buildamic things with vendor:publish but that didn’t do anything. Are we missing some publishables, or did I forget to set something up? In the console I get the following error: 

![Schermafbeelding 2021-09-03 om 13 37 45](https://user-images.githubusercontent.com/9193686/131999254-2fe87d88-b2bd-49bd-916a-0b2f2cd4df29.png)

## How to Reproduce
1. Install a new statamic project
2. `composer require handmadeweb/buildamic`
3. Navigate to a blueprint, and add a field.
4. The Buildamic SVG for the field type is missing

alternatively:
1. Install a new statamic project
2. `composer require handmadeweb/buildamic`
3. Add a buildamic field to a page blueprint (with a simple text field for example).
4. Now create a new page
5. Add a section, and edit the settings of this section. Notice that the text alignment icons are missing. The same is for row settings, and field settings.

## Extra Detail
![Schermafbeelding 2021-09-03 om 13 33 34](https://user-images.githubusercontent.com/9193686/131998935-f7404a32-69fb-4578-a725-8b8232aa12d6.png)
![Schermafbeelding 2021-09-03 om 13 35 58](https://user-images.githubusercontent.com/9193686/131999099-aac6671c-2a97-4b99-a8d8-70c130ddaedd.png)

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.6
edalzell/blade-directives 3.5
handmadeweb/buildamic dev-main

**Comment by michaelr0** [comment]
Thanks Jelle,

I have defined an icon for the Buildamic field type and changed the alignment icons to use the burger menu from Statamic's svg's

https://github.com/HandmadeWeb/buildamic/commit/bdf9b4b130f310600210522b11529e2a1d2398a5

![image](https://user-images.githubusercontent.com/54159303/132005562-211c0255-0b89-4fb2-9586-304e9b4e6103.png)

![image](https://user-images.githubusercontent.com/54159303/132005619-3b2e0327-2b9b-407e-b315-87b868a56de1.png)

@sliver37 do you have any changes?

**Comment by jelleroorda** [comment]
@michaelr0 The buildamic icon is fixed, however for the text alignment right now it's not clear that it's left-aligned, center-aligned or right-aligned right now.

See for example (old school) Word:
![Schermafbeelding 2021-09-03 om 14 42 19](https://user-images.githubusercontent.com/9193686/132006956-4603bf11-94b4-4fb5-9a1c-6eebc61a1be7.png)

**Comment by michaelr0** [comment]
https://github.com/HandmadeWeb/buildamic/commit/59bbd9845110b42f4f14cb2881e3ff5b6281663b and https://github.com/HandmadeWeb/buildamic/commit/63e5b59d3f81567a2ab8e3cfc762375420ec9ebf should fix those up.

**Comment by jelleroorda** [comment]
Thanks! It's fixed.
